name: Actions Workflow
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: hello world Action
        id: greet
        uses: gr2m/hello-world-js-action@v1.x
        with:
          greeting: Haidar
      - name: greeting time
        run: echo "${{ steps.greet.outputs.time }}"