name: shell commands
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello gitactions"
      - name: multiline script
        run: |
          node -v
          npm -v  