name: shell commands
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello gitactions"
      - name: multiline script
        run: |
          node -v
          npm -v  
      - name: python command
        run: |
          import platform
          print
          (platform.processor())
        shell: /usr/bin/python
    
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: powershell commands
        run: Get-Location
      - name: bash command
        run: pwd
        shell: bash